# Generated by Django 4.1.1 on 2022-11-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cedva1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='activo_por_pagos',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
